-- MySQL Script generated by MySQL Workbench
-- Sun Dec  2 10:33:38 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema la_casa_del_livro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema la_casa_del_livro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `la_casa_del_livro` DEFAULT CHARACTER SET latin1 ;
USE `la_casa_del_livro` ;

-- -----------------------------------------------------
-- Table `la_casa_del_livro`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `la_casa_del_livro`.`cliente` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `CPF` VARCHAR(11) NOT NULL,
  `Nome` VARCHAR(255) NOT NULL,
  `RG` VARCHAR(45) NOT NULL,
  `Sexo` VARCHAR(45) NOT NULL,
  `OrgaoEmissor` VARCHAR(45) NOT NULL,
  `UF` VARCHAR(45) NOT NULL,
  `DataNascimento` DATE NOT NULL,
  `EstadoCivil` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `TelefoneResidencial` VARCHAR(11) NULL DEFAULT NULL,
  `TelefoneCelular` VARCHAR(11) NOT NULL,
  `Rua` VARCHAR(255) NULL DEFAULT NULL,
  `Numero` VARCHAR(255) NULL DEFAULT NULL,
  `CEP` VARCHAR(255) NULL DEFAULT NULL,
  `Complemento` VARCHAR(255) NULL DEFAULT NULL,
  `Bairro` VARCHAR(255) NULL DEFAULT NULL,
  `Cidade` VARCHAR(255) NULL DEFAULT NULL,
  `Estado` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `la_casa_del_livro`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `la_casa_del_livro`.`produto` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(255) NOT NULL,
  `Autor` VARCHAR(255) NOT NULL,
  `Genero` VARCHAR(255) NOT NULL,
  `Editora` VARCHAR(255) NOT NULL,
  `Valor` DECIMAL(20,2) NOT NULL,
  `Tipo` VARCHAR(255) NOT NULL,
  `Quantidade` INT(11) NOT NULL,
  `Descricao` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `la_casa_del_livro`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `la_casa_del_livro`.`venda` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Data` DATETIME NOT NULL,
  `ValorTotal` DECIMAL(20,2) NOT NULL,
  `idCliente` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  INDEX `idCliente_idx` (`idCliente` ASC),
  CONSTRAINT `idCliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `la_casa_del_livro`.`cliente` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `la_casa_del_livro`.`vendaproduto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `la_casa_del_livro`.`vendaproduto` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `idProduto` INT(11) NOT NULL,
  `QuantidadeVenda` INT(11) NOT NULL,
  `idVenda` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `idProduto_idx` (`idProduto` ASC),
  INDEX `idVenda_idx` (`idVenda` ASC),
  CONSTRAINT `idProduto`
    FOREIGN KEY (`idProduto`)
    REFERENCES `la_casa_del_livro`.`produto` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idVenda`
    FOREIGN KEY (`idVenda`)
    REFERENCES `la_casa_del_livro`.`venda` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
